name: Generate Codebase Diagram (v6)
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      
      - name: Generate and commit diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
