name: Generate Codebase Diagram (v2)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout
      
    - name: Generate and commit diagram
      uses: githubocto/repo-visualizer

